
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getInstallations() : Promise<Result<Installation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModules() : Promise<ModuleInfo[]> {
    return await TAURI_INVOKE("get_modules");
},
async setModuleConfig(moduleId: string, config: ModuleConfig) : Promise<void> {
    await TAURI_INVOKE("set_module_config", { moduleId, config });
},
async getLanguagePack() : Promise<string | null> {
    return await TAURI_INVOKE("get_language_pack");
},
async setLanguagePack(path: string | null) : Promise<void> {
    await TAURI_INVOKE("set_language_pack", { path });
},
async getSelectedChannels() : Promise<string[]> {
    return await TAURI_INVOKE("get_selected_channels");
},
async setSelectedChannels(channels: string[]) : Promise<void> {
    await TAURI_INVOKE("set_selected_channels", { channels });
},
async patch(installations: Installation[]) : Promise<Result<PatchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch", { installations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removePatch(installations: Installation[]) : Promise<Result<RemoveResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_patch", { installations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ChoiceOption = { 
/**
 * Machine-readable value (used in config and code).
 */
value: string; 
/**
 * Human-readable label (displayed in UI).
 */
label: string }
/**
 * A discovered Star Citizen installation.
 */
export type Installation = { channel: string; path: string }
/**
 * Per-module configuration (from config.toml or GUI).
 */
export type ModuleConfig = { enabled: boolean | null; 
/**
 * User-chosen values keyed by option name.
 */
options?: OptionEntry[] }
/**
 * Serializable module metadata for the GUI.
 */
export type ModuleInfo = { id: string; name: string; description: string; default_enabled: boolean; enabled: boolean; needs_datacore: boolean; options: ModuleOption[]; 
/**
 * Persisted option values from disk. Empty if the user has not
 * customized this module — the UI should fall back to option defaults.
 */
option_values: OptionEntry[] }
/**
 * Describes a configurable option exposed by a module.
 */
export type ModuleOption = { 
/**
 * Machine-readable identifier (used in config and code).
 */
id: string; 
/**
 * Human-readable label (displayed in UI).
 */
label: string; description: string; kind: OptionKind; default: string }
/**
 * A single option value entry.
 */
export type OptionEntry = { name: string; value: OptionValue }
export type OptionKind = { type: "Bool" } | { type: "String" } | { type: "Choice"; choices: ChoiceOption[] }
/**
 * A user-chosen value for a module option.
 */
export type OptionValue = { type: "Bool"; value: boolean } | { type: "String"; value: string } | { type: "Choice"; value: string }
export type PatchResult = { channel: string; applied: number; total: number; warnings: string[]; error: string | null }
export type RemoveResult = { channel: string; removed: boolean; error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
