
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getInstallations() : Promise<Result<Installation[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModules() : Promise<ModuleInfo[]> {
    return await TAURI_INVOKE("get_modules");
},
async setModuleConfig(moduleId: string, config: ModuleConfig) : Promise<void> {
    await TAURI_INVOKE("set_module_config", { moduleId, config });
},
async getLanguagePack() : Promise<string | null> {
    return await TAURI_INVOKE("get_language_pack");
},
async setLanguagePack(path: string | null) : Promise<void> {
    await TAURI_INVOKE("set_language_pack", { path });
},
async getSelectedChannels() : Promise<string[]> {
    return await TAURI_INVOKE("get_selected_channels");
},
async setSelectedChannels(channels: string[]) : Promise<void> {
    await TAURI_INVOKE("set_selected_channels", { channels });
},
async patch(installations: Installation[]) : Promise<Result<PatchResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch", { installations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removePatch(installations: Installation[]) : Promise<Result<RemoveResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_patch", { installations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Errors that can stop a command from producing a result, or that
 * land in `PatchResult.error` / `RemoveResult.error` when a single
 * installation can't be processed.
 */
export type AppError = 
/**
 * Discovery (RSI launcher log parsing) failed at the OS level.
 */
{ code: "discovery_failed"; data: { message: string } } | 
/**
 * `tauri::async_runtime::spawn_blocking` join failed.
 */
{ code: "task_join_failed"; data: { message: string } } | 
/**
 * Could not open `Data.p4k`. Path missing, locked, or corrupted.
 */
{ code: "p4k_open_failed"; data: { path: string; message: string } } | 
/**
 * `Data/Localization/english/global.ini` is missing inside the
 * p4k. Game install is incomplete or shape changed.
 */
{ code: "global_ini_not_found" } | 
/**
 * UTF-16 decode of the base global.ini failed.
 */
{ code: "ini_decode_failed"; data: { message: string } } | 
/**
 * Writing the patched global.ini back to the install dir failed.
 */
{ code: "output_write_failed"; data: { message: string } } | 
/**
 * Removing a previously written patch (and clearing user.cfg)
 * failed.
 */
{ code: "output_remove_failed"; data: { message: string } } | 
/**
 * Any error that wasn't classified — surfaced raw inside a
 * localized "Unexpected error: {message}" frame.
 */
{ code: "unexpected"; data: { message: string } }
/**
 * Non-fatal issues collected during a patch run. Surfaced in
 * `PatchResult.warnings`. Module-level variants carry both the id
 * (used to look up the translated module name in the frontend
 * catalog) and the english name (fallback when no translation
 * exists for that module).
 */
export type AppWarning = 
/**
 * Could not load the community language pack from URL or path.
 */
{ code: "language_pack_load_failed"; data: { message: string } } | 
/**
 * Loaded the bytes but couldn't decode them as INI.
 */
{ code: "language_pack_decode_failed"; data: { message: string } } | 
/**
 * Module needs the DataCore but it wasn't extracted (e.g. the
 * p4k extraction step failed earlier in this run).
 */
{ code: "module_skipped_no_datacore"; data: { module_id: string; module_name: string } } | 
/**
 * Module needs the parsed locale map but it wasn't built.
 */
{ code: "module_skipped_no_locale"; data: { module_id: string; module_name: string } } | 
/**
 * `generate_renames` returned an error.
 */
{ code: "module_rename_failed"; data: { module_id: string; module_name: string; message: string } } | 
/**
 * `generate_patches` returned an error.
 */
{ code: "module_patch_failed"; data: { module_id: string; module_name: string; message: string } } | 
/**
 * Module emitted Replace ops without declaring `uses_replace_ops()`
 * — those ops were dropped to protect the user's language pack
 * values.
 */
{ code: "undeclared_replace_dropped"; data: { module_id: string; module_name: string; count: number } } | 
/**
 * Any non-fatal issue that wasn't classified.
 */
{ code: "unexpected"; data: { message: string } }
export type ChoiceOption = { 
/**
 * Machine-readable value (used in config and code).
 */
value: string; 
/**
 * Human-readable label (displayed in UI).
 */
label: string }
/**
 * A discovered Star Citizen installation.
 */
export type Installation = { channel: string; path: string }
/**
 * Per-module configuration (from config.toml or GUI).
 */
export type ModuleConfig = { enabled: boolean | null; 
/**
 * User-chosen values keyed by option name.
 */
options?: OptionEntry[] }
/**
 * Serializable module metadata for the GUI.
 */
export type ModuleInfo = { id: string; name: string; description: string; default_enabled: boolean; enabled: boolean; needs_datacore: boolean; 
/**
 * Whether this module emits `PatchOp::Replace` ops. See
 * [`Module::uses_replace_ops`].
 */
uses_replace_ops: boolean; options: ModuleOption[]; 
/**
 * Persisted option values from disk. Empty if the user has not
 * customized this module — the UI should fall back to option defaults.
 */
option_values: OptionEntry[] }
/**
 * Describes a configurable option exposed by a module.
 */
export type ModuleOption = { 
/**
 * Machine-readable identifier (used in config and code).
 */
id: string; 
/**
 * Human-readable label (displayed in UI).
 */
label: string; description: string; kind: OptionKind; default: string }
/**
 * Per-module outcome for a single patch run.
 */
export type ModuleStat = { module_id: string; module_name: string; 
/**
 * Number of (key, op) pairs this module emitted.
 */
patches: number; 
/**
 * Replace ops from this module that landed on a key another,
 * earlier-running module had already Replaced. The later Replace
 * wins and the earlier module's value is discarded. Aggregated by
 * the overridden module's name (→ number of overridden keys).
 */
replace_overrides: ReplaceOverride[] }
/**
 * A single option value entry.
 */
export type OptionEntry = { name: string; value: OptionValue }
export type OptionKind = { type: "Bool" } | { type: "String" } | { type: "Choice"; choices: ChoiceOption[] }
/**
 * A user-chosen value for a module option.
 */
export type OptionValue = { type: "Bool"; value: boolean } | { type: "String"; value: string } | { type: "Choice"; value: string }
export type PatchResult = { channel: string; applied: number; total: number; 
/**
 * Per-module patch counts and Replace-conflict details. One entry
 * per enabled module that ran, in the order they ran (priority).
 */
module_stats: ModuleStat[]; 
/**
 * True issues only — module errors, skips for missing datacore /
 * locale, etc. Not per-module stats (those are `module_stats`).
 */
warnings: AppWarning[]; error: AppError | null }
export type RemoveResult = { channel: string; removed: boolean; error: AppError | null }
/**
 * Aggregated count of Replace conflicts against a single earlier module.
 */
export type ReplaceOverride = { 
/**
 * Name of the earlier module whose Replace was overridden.
 */
overrode_module: string; keys: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
