[module]
name = "Blueprint Markers"
description = "Add [BP] tag to contract titles that reward blueprints"
default_enabled = false


[[patch]]
keys = [
  "CFP_RecoverCargo_Easy_Title",
  "CFP_RecoverCargo_Hard_Title",
  "CFP_RecoverCargo_Medium_Title",
  "CFP_RecoverCargo_Super_Title",
  "CFP_RecoverCargo_VeryHard_Title",
  "Foxwell_DefendLocation_E_Title_001",
  "Foxwell_DefendLocation_H_Title_001",
  "Foxwell_DefendLocation_M_Title_001",
  "Foxwell_DefendLocation_S_Title_001",
  "Foxwell_DefendLocation_VE_Title_001",
  "Foxwell_DefendLocation_VH_Title_001",
  "Foxwell_DestroyNarcotics_E_title_001",
  "Foxwell_DestroyNarcotics_H_title_001",
  "Foxwell_DestroyNarcotics_M_title_001",
  "Foxwell_EliminateAll_Allies_title_001",
  "Foxwell_EliminateAll_NonHostiles_title_001",
  "Foxwell_EliminateAll_OLP_M_title_001",
  "Foxwell_EliminateAll_PAF_M_title_001",
  "Foxwell_EliminateAll_title_001",
  "Foxwell_EliminateSpecific_NonHostiles_title_001",
  "Foxwell_EliminateSpecific_title_001",
  "Foxwell_HaulCargo_AToB_OLP_title_01",
  "Foxwell_HaulCargo_AToB_PAF_title_01",
  "Foxwell_HaulCargo_MultiToSingle_title_01",
  "Foxwell_Mercenary_Rehire_title_001",
  "Foxwell_SecurityPatrol_E_Title_001",
  "Foxwell_SecurityPatrol_H_Title_001",
  "Foxwell_SecurityPatrol_M_Title_001",
  "Foxwell_SecurityPatrol_S_Title_001",
  "Foxwell_SecurityPatrol_VE_Title_001",
  "Foxwell_SecurityPatrol_VH_Title_001",
  "Foxwell_ShipAmbush_E_title_001",
  "Foxwell_ShipAmbush_H_title_001",
  "Foxwell_ShipAmbush_M_title_001",
  "Foxwell_ShipAmbush_S_title_001",
  "Foxwell_ShipAmbush_VE_title_001",
  "Foxwell_ShipAmbush_VH_title_001",
  "Foxwell_ShipWaveAttack_ClearHostiles_Title_E_001",
  "Foxwell_ShipWaveAttack_ClearHostiles_Title_H_001",
  "Foxwell_ShipWaveAttack_ClearHostiles_Title_M_001",
  "Foxwell_ShipWaveAttack_ClearHostiles_Title_VE_001",
  "Foxwell_bombingrun_E_title_001",
  "Foxwell_bombingrun_H_title_001",
  "Foxwell_bombingrun_M_title_001",
  "Foxwell_bombingrun_S_title_001",
  "Foxwell_bombingrun_VE_title_001",
  "Foxwell_bombingrun_VH_title_001",
  "Headhunters_defend_XT_H_title_001",
  "Headhunters_defend_XT_VH_title_001",
  "Headhunters_eliminateall_caves_title_01",
  "Highpoint_KillAnimals_rockcracker_title_E_001",
  "Hockrow_FacilityDelve_P2M1_Repeat_title",
  "Hockrow_FacilityDelve_P2M2_Repeat_title",
  "Hockrow_FacilityDelve_P2M3_Repeat_title",
  "Hockrow_FacilityDelve_P2M4_Repeat_title",
  "Hockrow_FacilityDelve_P3M1_title,P",
  "InterSec_KillShip_Vanduul_Title_Super_001",
  "InterSec_ResourceGathering_Cryopods_Title",
  "InterSec_ResourceGathering_Tech_Title",
  "InterSec_SecurityPatrol_H_Title_001",
  "InterSec_SecurityPatrol_S_Title_001",
  "InterSec_SecurityPatrol_VH_Title_001",
  "Intersec_DefendShip_Title_Easy_001",
  "Intersec_DefendShip_Title_Hard_001",
  "Intersec_DefendShip_Title_Medium_001",
  "Intersec_DefendShip_Vanduul_Title_Super_001",
  "Intersec_DefendShip_Vanduul_Title_VeryHard_001",
  "Intersec_KillShip_Title_Easy_001",
  "Intersec_KillShip_Title_Hard_001",
  "Intersec_KillShip_Title_Intro_001",
  "Intersec_KillShip_Title_Medium_001",
  "Intersec_KillShip_Vanduul_Title_VeryHard_001",
  "Kaboos_Mission_Title",
  "LOC_UNINITIALIZED",
  "RAIN_collectresources_multiple_OLP_name_01",
  "RAIN_collectresources_single_OLP_name_01",
  "Shubin_Industrial_HandMining_Intro_Local_Title_001",
  "Shubin_Industrial_HandMining_Pyro_E_Local_Title_001",
  "Shubin_Industrial_HandMining_Pyro_H_PlanetarySystem_Title_001",
  "Shubin_Industrial_HandMining_Pyro_M_DiscoverPlanetary_Title_001",
  "Shubin_Industrial_HandMining_Pyro_Nyx_VH_Interstellar_Title_001",
  "Shubin_Industrial_HandMining_Pyro_VH_Interstellar_Title_001",
  "Shubin_Industrial_HandMining_Stanton_E_Local_Title_001",
  "Shubin_Industrial_HandMining_Stanton_E_PlanetarySystem_Title_001",
  "Shubin_Industrial_HandMining_Stanton_H_PlanetarySystem_Title_001",
  "Shubin_Industrial_HandMining_Stanton_H_Planetary_Solar_Title_001",
  "Shubin_Industrial_HandMining_Stanton_M_DiscoverPlanetary_Title_001",
  "Shubin_Industrial_HandMining_Stanton_VH_Solar_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_E_Local_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_H_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_M_Solar_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_S_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_VE_Local_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_VH_Interstellar_Title_001",
  "Shubin_Industrial_ShipMining_Nyx_VH_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_E_Local_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_H_PrimarySecondary_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_H_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_M_Solar_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_S_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Pyro_VH_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_E_Local_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_H_PrimarySecondary_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_H_Secondary_Interstellar_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_H_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_M_Solar_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_S_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_VE_Local_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_VH_Interstellar_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_VH_Secondary_Interstellar_Title_001",
  "Shubin_Industrial_ShipMining_Stanton_VH_Secondary_Title_001",
  "Shubin_Industrial_ShipMining_VH_Org_Title_001",
  "Vaughn_EliminateBoss_FPS_Rockcracker_Warehouse_name_001",
  "Vaughn_EliminateSpecific_FPS_Rockcracker_title_001",
  "Vaughn_EliminateSpecific_FPS_storm_H_title_001",
  "bhg_EliminateBoss_FPS_Rockcracker_Warehouse_name_001",
  "bhg_bounty_title_ASD_Engineering_001",
  "bhg_bounty_title_ASD_Research_001",
  "bhg_bounty_title_Rockcracker_001",
  "blackbox_recover_title_intro_001",
  "cfp_ChainElimAll_1C_ElimSpec_GenAttack_E_title_001",
  "cfp_ChainElimAll_1C_ElimSpec_HHAttack_M_title_001",
  "cfp_ChainElimAll_1C_HHAttack_M_title_001",
  "cfp_ChainElimAll_2C_ElimSpec_GenAttack_M_title_001",
  "cfp_ChainElimAll_2C_ElimSpec_HHAttack_H_title_001",
  "cfp_ChainElimAll_2C_ElimSpec_XTAttack_H_title_001",
  "cfp_ChainElimAll_3C_ElimSpec_GenAttack_M_title_001",
  "cfp_ChainElimAll_3C_ElimSpec_HHAttack_VH_title_001",
  "cfp_ChainElimAll_3C_ElimSpec_XTAttack_VH_title_001",
  "cfp_bombingrun_E_title_001",
  "cfp_bombingrun_sabotage_generators_title_001",
  "cfp_defend-criminals_title_001",
  "cfp_defend-xenothreat_title_001",
  "cfp_defend-xenothreat_title_002",
  "cfp_defend-xenothreat_title_003",
  "cfp_defend_boss_Generic_title_001",
  "cfp_defend_cave_Generic_title_001",
  "cfp_defend_headhunters_H_title_001",
  "cfp_defend_headhunters_M_title_001",
  "cfp_defend_regionshift_title_001",
  "cfp_defendship_multi_SRT_title_001",
  "cfp_defendship_multi_VHRT_title_001",
  "cfp_delivery_eliminateall_sabotage_server_H_XT_title_001",
  "cfp_eliminateall_XT_E_title_001",
  "cfp_eliminateall_fromCFP_Gen_E_title_001",
  "cfp_eliminateall_fromCFP_hh_M_title_001",
  "cfp_eliminateall_hh_E_title_001",
  "cfp_sabotage_VH_title_001",
  "cfp_sabotage_drugs_M_title_001",
  "cfp_sabotage_generators_E_HH_title_001",
  "cfp_sabotage_generators_H_title_001",
  "cfp_sabotage_generators_M_title_001",
  "cfp_sabotage_generators_VE_title_001",
  "cfp_sabotage_server_elimiatespecific_HH_title_001",
  "cfp_sabotage_servers_E_HH_title_001",
  "cfp_sabotage_servers_H_XT_title_001",
  "cfp_sabotage_servers_M_HH_title_001",
  "cfp_sabotage_servers_M_title_001",
  "cfp_sabotage_servers_VH_XT_title_001",
  "destroyprobelegal_title",
  "eckhart_defendship_LRT_title_001",
  "eckhart_defendship_MRT_title_001",
  "eckhart_defendship_VLRT_title_001",
  "eckhart_defendship_multi_HRT_title_001",
  "eckhart_defendship_multi_SRT_title_001",
  "eckhart_defendship_multi_VHRT_title_001",
  "foxwell_DefendShip_E_title_001",
  "foxwell_DefendShip_H_title_001",
  "foxwell_DefendShip_M_title_001",
  "headhunters_ChainElimAll_1C_AttackCFP_E_title_001",
  "headhunters_ChainElimAll_1C_AttackXT_M_title_001",
  "headhunters_ChainElimAll_1C_ElimSpec_AttackCFP_M_title_001",
  "headhunters_ChainElimAll_2C_ElimSpec_AttackCFP_H_title_001",
  "headhunters_ChainElimAll_2C_ElimSpec_AttackXT_H_title_001",
  "headhunters_ChainElimAll_3C_ElimSpec_AttackCFP_VH_title_001",
  "headhunters_ChainElimAll_3C_ElimSpec_AttackXT_VH_title_001",
  "headhunters_ChainElimAll_AttackCFP_E_title_001",
  "headhunters_ChainElimAll_AttackGen_E_title_001",
  "headhunters_ChainElimAll_Boss_XenoThreat_VH_title_001",
  "headhunters_EliminateAll_XenoThreat_H_title_001",
  "headhunters_EliminateSpecific_Asteroid_Generic_M_title_001",
  "headhunters_EliminateSpecific_Asteroid_Generic_VE_title_001",
  "headhunters_EliminateSpecific_CFP_E_title_001",
  "headhunters_EliminateSpecific_CFP_H_title_001",
  "headhunters_EliminateSpecific_CFP_M_title_001",
  "headhunters_EliminateSpecific_Carvers_XenoThreat_H_title_001",
  "headhunters_EliminateSpecific_Defector_title_001",
  "headhunters_EliminateSpecific_Generic_E_title_001",
  "headhunters_EliminateSpecific_Generic_M_title_001",
  "headhunters_EliminateSpecific_Generic_VH_title_001",
  "headhunters_EliminateSpecific_Riviera_XenoThreat_VH_title_001",
  "headhunters_EliminateSpecific_TheYard_XenoThreat_H_title_001",
  "headhunters_EliminateSpecific_Windfall_XenoThreat_H_title_001",
  "headhunters_EliminateSpecific_XenoThreat_H_title_001",
  "headhunters_EliminateSpecific_XenoThreat_VH_title_001",
  "headhunters_EliminateSpecific_XenoThreat_title_001",
  "headhunters_defend_Generic_M_Carvers_title_001",
  "headhunters_defend_Generic_M_GoldenRivera_title_001",
  "headhunters_defend_Generic_M_TheYard_title_001",
  "headhunters_defend_Generic_M_WindFall_title_001",
  "headhunters_defend_Generic_M_title_001",
  "headhunters_defend_xt_title_001",
  "headhunters_eliminateall_Generic_M_title_001",
  "headhunters_eliminateall_XT_derelicts_title_01",
  "headhunters_eliminateall_base_Generic_E_title_001",
  "headhunters_eliminateall_cfp_E_title_001",
  "headhunters_eliminateall_cfp_M_title_001",
  "headhunters_eliminateall_cfp_title_001",
  "headhunters_eliminateall_outpost_title_01",
  "headhunters_eliminateall_retrievestolen_base_Generic_M_title_001",
  "headhunters_eliminateall_retrievestolen_missingperson_base_Generic_M_title_001",
  "headhunters_eliminateall_xt_title_001",
  "hh_killanimals_e_derelictoutpostscaves_title_001",
  "hh_killanimals_h_derelictoutpostscaves_title_001",
  "hh_killanimals_m_derelictoutpostscaves_title_001",
  "northrock_bounty_fps_title_001",
  "recovery_title",
  "shubin_rockcracker_pvp_title_01",
  "shubin_rockcracker_solo_title_01",
  "vaughn_assassination_FPS_UGF_illegal_title_001",
]
suffix = " <EM4>[BP]</EM4>"
